/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnnouncementId = IDL.Nat;
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'whatsapp' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const PrayerTimes = IDL.Record({
  'asr' : IDL.Text,
  'maghrib' : IDL.Text,
  'juma_khutba' : IDL.Text,
  'fajr' : IDL.Text,
  'isha' : IDL.Text,
  'zohar' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAnnouncementsByDate' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getPrayerTimes' : IDL.Func([], [PrayerTimes], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAnnouncement' : IDL.Func(
      [AnnouncementId, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updatePrayerTimes' : IDL.Func([PrayerTimes], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnnouncementId = IDL.Nat;
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'whatsapp' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PrayerTimes = IDL.Record({
    'asr' : IDL.Text,
    'maghrib' : IDL.Text,
    'juma_khutba' : IDL.Text,
    'fajr' : IDL.Text,
    'isha' : IDL.Text,
    'zohar' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAnnouncementsByDate' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getPrayerTimes' : IDL.Func([], [PrayerTimes], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAnnouncement' : IDL.Func(
        [AnnouncementId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updatePrayerTimes' : IDL.Func([PrayerTimes], [], []),
  });
};

export const init = ({ IDL }) => { return []; };